app = 'spectra-frontend'
primary_region = 'ord'

[build]
  image = 'ghcr.io/valospectra/overlay:latest'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[files]]
  guest_path = '/usr/share/nginx/html/assets/config/config.json'
  local_path = './config/config.json'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
